package net.rbk.froglins.Entidades.Animaciones;


import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;
public class WollyFroglinAnimaciones {
    public static final AnimationDefinition CHARGE = AnimationDefinition.Builder.withLength(3.5f)
            .addAnimation("BrazoIzq",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.25f, KeyframeAnimations.posVec(0f, -4f, 3f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -6f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.posVec(0f, -8f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.5f, KeyframeAnimations.posVec(0f, -8f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.6766667f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("BrazoIzq",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-47.37f, 31.26f, 9.36f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-100.37f, 3.28f, -21.17f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(-167.74f, 9.43f, -7.35f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.5f, KeyframeAnimations.degreeVec(-167.74f, 9.43f, -7.35f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(103.09f, 17.07f, 3.9f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.degreeVec(103.09f, 17.07f, 3.9f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("BrazoDer",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.25f, KeyframeAnimations.posVec(0f, -4f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -6f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.posVec(0f, -8f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.5f, KeyframeAnimations.posVec(0f, -8f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.6766667f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("BrazoDer",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-75f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-115.69f, -26.49f, -7.67f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(-166.22f, -9.83f, -1.64f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.5f, KeyframeAnimations.degreeVec(-166.22f, -9.83f, -1.64f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(103.09f, 17.07f, 3.9f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.degreeVec(103.09f, 17.07f, 3.9f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Cabeza",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Cabeza",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-15.92f, 19.29f, -5.38f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-30.76f, -12.46f, 8.81f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-45.2f, 4.75f, -5.74f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(-60f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.5f, KeyframeAnimations.degreeVec(-60f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(77.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.degreeVec(77.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2.25f, KeyframeAnimations.degreeVec(58.1f, 18.06f, 24.37f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-5f, -27.5f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2.75f, KeyframeAnimations.degreeVec(5f, 25f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.degreeVec(-2.5f, -35f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3.25f, KeyframeAnimations.degreeVec(2.5f, 20f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("mandibulaInf",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.75f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("mandibulasup",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(-42.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.5f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR))).build();
}
